name: Build-test docs

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .
          pip3 install -r docs/requirements.txt

      - name: Build the docs
        run: |
          sphinx-build docs/source docs/build

      - name: Test the docs
        run: |
          sphinx-build docs/source docs/build -b doctest
